import math
import random


def metropolis_hastings(
    target_density,
    x0,
    n_samples,
    proposal_std=1.0,
    seed=None
):
    """
    Metropolis-Hastings MCMC sampling.

    Parameters
    ----------
    target_density : function
        The target probability density p(x).
        We only need to be able to EVALUATE p(x).
        We do NOT need to sample from it directly.

    x0 : float
        Initial state of the Markov chain.

    n_samples : int
        Number of MCMC iterations.

    proposal_std : float
        Standard deviation of the Gaussian proposal distribution.

    seed : int, optional
        Random seed for reproducibility.

    Returns
    -------
    samples : list
        Samples generated by the Markov chain.

    acceptance_rate : float
        Fraction of proposed moves that were accepted.
    """

    # ---------------------------------------------------------
    # 1. Set random seed
    # ---------------------------------------------------------
    if seed is not None:
        random.seed(seed)

    # ---------------------------------------------------------
    # 2. Start the Markov chain at x0
    #
    # Theory:
    #       x_0 = initial state
    # ---------------------------------------------------------
    x_current = x0

    # Store the initial state as the first sample.
    samples = [x_current]

    # Count how many proposals were accepted.
    accepted = 0

    # ---------------------------------------------------------
    # 3. Repeat the Metropolis-Hastings procedure
    # ---------------------------------------------------------
    for _ in range(n_samples):

        # =====================================================
        # STEP 1: PROPOSE A NEW STATE
        # =====================================================
        #
        # We use a Gaussian random-walk proposal:
        #
        #       x' ~ N(x_current, proposal_std^2)
        #
        # Equivalently:
        #
        #       x' = x_current + epsilon
        #
        # where:
        #
        #       epsilon ~ N(0, proposal_std^2)
        #
        # Because this Gaussian is centered at x_current,
        # the proposal is symmetric:
        #
        #       q(x' | x) = q(x | x')
        #
        # -----------------------------------------------------

        epsilon = random.gauss(0, proposal_std)

        x_proposed = x_current + epsilon

        # =====================================================
        # STEP 2: EVALUATE THE TARGET DENSITY
        # =====================================================
        #
        # We calculate:
        #
        #       p(x_current)
        #       p(x_proposed)
        #
        # We do NOT need to sample from p(x).
        # We only need to evaluate it.
        # -----------------------------------------------------

        current_probability = target_density(x_current)

        proposed_probability = target_density(x_proposed)

        # =====================================================
        # STEP 3: CALCULATE THE ACCEPTANCE RATIO
        # =====================================================
        #
        # General Metropolis-Hastings:
        #
        #   alpha =
        #
        #       p(x') q(x_current | x')
        #       -------------------------
        #       p(x)  q(x' | x)
        #
        # Since our proposal is symmetric:
        #
        #       q(x' | x) = q(x | x')
        #
        # the proposal terms cancel.
        #
        # Therefore:
        #
        #       alpha =
        #
        #       p(x') / p(x)
        #
        # -----------------------------------------------------

        acceptance_ratio = (
            proposed_probability / current_probability
        )

        # =====================================================
        # STEP 4: MAKE SURE ACCEPTANCE PROBABILITY <= 1
        # =====================================================
        #
        # A probability cannot be greater than 1.
        #
        # Therefore:
        #
        #       alpha = min(1, acceptance_ratio)
        #
        # Example:
        #
        #   ratio = 2.5  -> alpha = 1
        #   ratio = 0.4  -> alpha = 0.4
        #
        # -----------------------------------------------------

        acceptance_probability = min(
            1.0,
            acceptance_ratio
        )

        # =====================================================
        # STEP 5: GENERATE A RANDOM NUMBER
        # =====================================================
        #
        # Generate:
        #
        #       U ~ Uniform(0, 1)
        #
        # We will accept the proposal if:
        #
        #       U < acceptance_probability
        #
        # -----------------------------------------------------

        random_number = random.random()

        # =====================================================
        # STEP 6: ACCEPT OR REJECT THE PROPOSAL
        # =====================================================

        if random_number < acceptance_probability:

            # -------------------------------------------------
            # ACCEPT
            #
            # The proposed state becomes the next state:
            #
            #       x_(t+1) = x'
            # -------------------------------------------------

            x_current = x_proposed

            accepted += 1

        else:

            # -------------------------------------------------
            # REJECT
            #
            # IMPORTANT:
            #
            # We do NOT generate another value.
            #
            # We simply stay at the current state:
            #
            #       x_(t+1) = x_t
            # -------------------------------------------------

            x_current = x_current

        # =====================================================
        # STEP 7: RECORD THE CURRENT STATE
        # =====================================================
        #
        # Whether we accepted or rejected:
        #
        #       record x_(t+1)
        #
        # If rejected, this means the same value gets recorded
        # again.
        #
        # Example:
        #
        #       2.5 -> proposal 5.0 -> REJECT
        #
        # The chain becomes:
        #
        #       2.5, 2.5
        #
        # This repeated value is important and must be kept.
        # -----------------------------------------------------

        samples.append(x_current)

    # =========================================================
    # STEP 8: CALCULATE ACCEPTANCE RATE
    # =========================================================

    acceptance_rate = accepted / n_samples

    return samples, acceptance_rate

def normal_density(x, mean=3.0, std=0.5):
    """
    Probability density of a normal distribution.
    """

    coefficient = 1 / (
        math.sqrt(2 * math.pi) * std
    )

    exponent = -((x - mean) ** 2) / (
        2 * std ** 2
    )

    probability = coefficient * math.exp(exponent)

    return probability

samples, acceptance_rate = metropolis_hastings(
    target_density=normal_density,
    x0=0.0,
    n_samples=5000,
    proposal_std=1.0,
    seed=42
)

burn_in = 500

kept_samples = samples[burn_in:]

def calculate_mean(values):
    total = 0

    for value in values:
        total += value

    mean = total / len(values)

    return mean


def calculate_variance(values):
    mean = calculate_mean(values)

    total = 0

    for value in values:
        difference = value - mean
        total += difference ** 2

    variance = total / len(values)

    return variance

mean = calculate_mean(kept_samples)
variance = calculate_variance(kept_samples)

print("Acceptance rate :", acceptance_rate)
print("Sample mean     :", mean)
print("Sample variance :", variance)

print("True mean       :", 3.0)
print("True variance   :", 0.25)